# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 941d58b8a6ada5615d72ffcac349b68b6aeea3ccd11a00275098a481e5373e64cc986d6c9c7374a0dc3ac4fdfd2b39fc732f32d37227db2feb3547f9ba18a3cb

test:
  secret_key_base: 7cd6cd8b8bb57ddec2d2e800792d6012af5defe7cbcf1b664f80b71b91d8b553b2b4b60fc705d1d8e68043742af60ec0174d00a9b3bf68311e6a75c3f8716cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
